version: '3'

services:
  # docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx
  lb:
    image: nginx:alpine
    volumes:
    # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/html:/usr/share/nginx/html
    ports:
    - 8080:80
