version: '3'

services:
  # docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx
  lb:
    image: nginx:alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/html:/usr/share/nginx/html
    ports:
    - 8080:80
  server1:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - INSTANCE_NAME="server 1"
      - PUBLIC_PORT="8081"
    volumes:
      - ./servers:/home/node/app
    ports:
      - "8081:3000"
    command: "npm start"
  server2:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - INSTANCE_NAME="server 2"
      - PUBLIC_PORT="8082"
    volumes:
      - ./servers:/home/node/app
    ports:
      - "8082:3000"
    command: "npm start"
