version: '3'

services:
  # MySQL
  db-master:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/dbm/data:/var/lib/mysql
    - ./docker/dbm/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/dbm/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  db-slave1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/dbs1/data:/var/lib/mysql
    - ./docker/dbs1/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/dbs1/sql:/docker-entrypoint-initdb.d
    ports:
    - 3406:3306
